### ISSUE TITLE
Not working for some browsers

### ISSUE THREAD

**Issue by eebbesen** [eebbesen/ineedagyro-js#33]
Just spinning gyro -- figure out way to instrument that problem to be alerted when it happens and/or capture logs to help fix it.

**Comment by eebbesen** [comment]
Need to have better logging around not being able to get location information. I can see requests coming in but the gyro just continues to spin (Chrome from Erik's laptop). 

My assumption is that the location request is bad. 

This has also been reported on mobile for some folks.
```
2017-08-18T17:39:47.397060+00:00 heroku[router]: at=info method=GET path="/" host=ineedagyro.herokuapp.com request_id=81885775-9520-4a64-b11a-8f0f076c962f fwd="209.134.145.18" dyno=web.1 connect=1ms service=3ms status=304 bytes=151 protocol=http
2017-08-18T17:39:48.008097+00:00 heroku[router]: at=info method=GET path="/images/gyro_2.png" host=ineedagyro.herokuapp.com request_id=ae2ce847-7ba0-48fc-87c6-feee45f6c723 fwd="209.134.145.18" dyno=web.1 connect=1ms service=36ms status=200 bytes=610121 protocol=http
```

**Comment by eebbesen** [comment]
Here's one example:
```
View.js:44 Uncaught DOMException: Blocked a frame with origin "https://ineedagyro.herokuapp.com" from accessing a cross-origin frame.
    at chrome-extension://ihbdojmggkmjbhfflnchljfkgdhokffj/js/content/View.js:44:27
    at chrome-extension://ihbdojmggkmjbhfflnchljfkgdhokffj/js/content/View.js:809:3
(anonymous) @ View.js:44
(anonymous) @ View.js:809
ContentSelector.js:140 Uncaught DOMException: Blocked a frame with origin "https://ineedagyro.herokuapp.com" from accessing a cross-origin frame.
    at chrome-extension://ihbdojmggkmjbhfflnchljfkgdhokffj/js/content/ContentSelector.js:140:24
    at chrome-extension://ihbdojmggkmjbhfflnchljfkgdhokffj/js/content/ContentSelector.js:210:3
(anonymous) @ ContentSelector.js:140
(anonymous) @ ContentSelector.js:210
2script.js:38 [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```

**Comment by eebbesen** [comment]
Now adding an error message, but this will probably get more diagnosable once we move to browser-based ajax from current server-based ajax.

**Comment by eebbesen** [comment]
Added logging -- I think this is mostly not being able to get location info
